import { x25519 } from '@noble/curves/ed25519.js';
import { bytesToHex, concatBytes, randomBytes } from '@noble/curves/utils.js';
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import { hkdf } from '@noble/hashes/hkdf.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { randomUUID } from 'expo-crypto';

const NONCE_LENGTH = 24;

/**
 * Generates a locally-unique, self-assigned ID (a native RFC4122 UUID v4).
 * One generator, used directly wherever an entity (a circle, a member, a
 * post, ...) needs an ID — no per-entity wrapper function, so adding a new
 * entity type never means adding a new method here that just forwards to
 * this one.
 *
 * For anything a *member* self-assigns to reference themselves (like a
 * post's author, or their own roster entry), it must be generated by that
 * member at the moment they need it, never derived from other members'
 * existing state — that's what lets every device replay the same event
 * and agree on the same ID with zero coordination.
 */
export function generateUUID(): string {
  return randomUUID();
}

export type Keypair = {
  publicKey: Uint8Array;
  secretKey: Uint8Array;
};

/**
 * Digits 1-9 plus A-Z minus I/L/O — drops the pairs most often misread
 * (0/O, 1/I/L) when handwritten or read aloud. Exactly 32 symbols so each
 * one maps to 5 bits of a random byte with zero modulo bias (256 / 32 = 8).
 */
const INVITE_CODE_ALPHABET = '123456789ABCDEFGHJKMNPQRSTUVWXYZ';

/**
 * Generates a circle invite code: 12 random characters from a
 * confusion-resistant alphabet, grouped for readability (`XXXX-XXXX-XXXX`).
 * 60 bits of entropy — short enough to read aloud or type by hand, unlike
 * a full UUID, while still being infeasible to guess within an invite's
 * short lifetime. The same string backs both the shareable link and the
 * QR code — there's only ever one secret here, just two presentations of it.
 *
 * Not invite-specific despite the name: device-transfer reuses it verbatim
 * for its own one-time code, the same way it reuses the invite mailbox.
 */
export function generateInviteCode(): string {
  const bytes = randomBytes(12);
  const chars = Array.from(bytes, (byte) => INVITE_CODE_ALPHABET[byte % INVITE_CODE_ALPHABET.length]);
  return [chars.slice(0, 4), chars.slice(4, 8), chars.slice(8, 12)].map((group) => group.join('')).join('-');
}

/**
 * Encrypts `plaintext` under the circle's shared secret using
 * XChaCha20-Poly1305 (AEAD — tampering makes decrypt fail, it doesn't
 * silently return corrupted data). A fresh random nonce is generated per
 * call and prepended to the returned bytes, since decrypt needs it back.
 */
export function encrypt(plaintext: Uint8Array, secret: Uint8Array): Uint8Array {
  const nonce = randomBytes(NONCE_LENGTH);
  const ciphertext = xchacha20poly1305(secret, nonce).encrypt(plaintext);
  return concatBytes(nonce, ciphertext);
}

/**
 * Encrypts a JSON-serializable value under any of this file's derived
 * secrets — an invite preview, a join request, the account manifest, a
 * device-transfer payload. A thin convenience over `encrypt` for
 * structured data instead of raw bytes; log entries go through
 * `buildAndEncryptLogEntry` instead, since those need a signature too.
 */
export function encryptJSON(value: unknown, secret: Uint8Array): Uint8Array {
  return encrypt(new TextEncoder().encode(JSON.stringify(value)), secret);
}

/**
 * Decrypts what `encrypt` produced: splits the leading nonce back off,
 * then decrypts the rest. Throws if the ciphertext was tampered with or
 * `secret` doesn't match what it was encrypted under.
 */
export function decrypt(ciphertext: Uint8Array, secret: Uint8Array): Uint8Array {
  const nonce = ciphertext.subarray(0, NONCE_LENGTH);
  const box = ciphertext.subarray(NONCE_LENGTH);
  return xchacha20poly1305(secret, nonce).decrypt(box);
}

/**
 * `sha256(bytes)`, hex-encoded. A post carries the hash of its photo inside
 * its ciphertext, so a device can check that the bytes it downloads are the
 * ones that were posted; the photo queue refuses a mismatch.
 */
export function hashBytes(bytes: Uint8Array): string {
  return bytesToHex(sha256(bytes));
}

const SEALED_BOX_KEY_DOMAIN = new TextEncoder().encode('join-approval-box');
const X25519_PUBLIC_KEY_LENGTH = 32;

/**
 * Generates a fresh one-time X25519 keypair for a single handshake message
 * — never reused, never persisted beyond that one exchange. Used for the
 * asymmetric half of the invite flow (see `sealToPublicKey`), where a
 * per-message keypair is what lets the recipient decrypt without ever
 * needing to know the sender's identity in advance.
 */
export function generateEphemeralKeypair(): Keypair {
  return x25519.keygen();
}

/**
 * Derives the AEAD key for one sealed-box message from its ECDH shared
 * secret. Binding both public keys into the HKDF info (not just the raw
 * shared secret) is standard sealed-box practice — it ties the derived key
 * to this specific sender/recipient pairing, the same way every other
 * derived key in this file is domain-separated rather than using raw key
 * material directly.
 */
function sealedBoxKey(sharedSecret: Uint8Array, senderPublicKey: Uint8Array, recipientPublicKey: Uint8Array): Uint8Array {
  return hkdf(sha256, sharedSecret, undefined, concatBytes(SEALED_BOX_KEY_DOMAIN, senderPublicKey, recipientPublicKey), 32);
}

/**
 * Seals `plaintext` to `recipientPublicKey` (X25519) — the asymmetric half
 * of the invite flow, used only for the approval response, the one
 * payload that must be readable by exactly one person. Generates a
 * fresh one-time keypair for this message alone, ECDHs it against the
 * recipient, derives an AEAD key from the shared secret via
 * `sealedBoxKey`, then encrypts with the same `encrypt()` every other
 * ciphertext in this file uses. The sender's ephemeral public key is
 * prepended to the output, so the recipient can open this with nothing
 * but their own secret key — no sender identity needs to be known in
 * advance.
 */
export function sealToPublicKey(plaintext: Uint8Array, recipientPublicKey: Uint8Array): Uint8Array {
  const ephemeral = x25519.keygen();
  const shared = x25519.getSharedSecret(ephemeral.secretKey, recipientPublicKey);
  const key = sealedBoxKey(shared, ephemeral.publicKey, recipientPublicKey);
  return concatBytes(ephemeral.publicKey, encrypt(plaintext, key));
}

/**
 * Opens what `sealToPublicKey` produced, using `recipientKeypair`'s own
 * secret key — the only thing the recipient needs, since the sender's
 * ephemeral public key travels inside `sealed` itself. Throws if `sealed`
 * was tampered with or doesn't match `recipientKeypair`.
 */
export function openSealedBox(sealed: Uint8Array, recipientKeypair: Keypair): Uint8Array {
  const senderPublicKey = sealed.subarray(0, X25519_PUBLIC_KEY_LENGTH);
  const box = sealed.subarray(X25519_PUBLIC_KEY_LENGTH);
  const shared = x25519.getSharedSecret(recipientKeypair.secretKey, senderPublicKey);
  const key = sealedBoxKey(shared, senderPublicKey, x25519.getPublicKey(recipientKeypair.secretKey));
  return decrypt(box, key);
}
